# Site settings
title: "Patrick Zhang"
description: >
  A personal blog. Copied from Frank hehe

author: Patrick Zhang
email: patrickzhangyf@gmail.com
twitter_username:
github_username: yanfii

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yanfii.github.io/" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:
comments: false

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title

sass:
    style: compressed

exclude: [vendor]
